"""Rename genre for artist

Revision ID: 15578d29b712
Revises: 65f64107050a
Create Date: 2020-05-10 12:20:37.935668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15578d29b712'
down_revision = '65f64107050a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ArtistGenre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genre',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Genre_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='Genre_artist_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Genre_pkey')
    )
    op.drop_table('ArtistGenre')
    # ### end Alembic commands ###
