"""making show and artist 1to1 to match specification

Revision ID: 1d8cfeccb48b
Revises: 9ee22db5487c
Create Date: 2020-04-20 18:51:47.768099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8cfeccb48b'
down_revision = '9ee22db5487c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_artists')
    op.add_column('Show', sa.Column('artist', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Show', 'Artist', ['artist'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_column('Show', 'artist')
    op.create_table('show_artists',
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='show_artists_artist_id_fkey'),
    sa.ForeignKeyConstraint(['show_id'], ['Show.id'], name='show_artists_show_id_fkey'),
    sa.PrimaryKeyConstraint('show_id', 'artist_id', name='show_artists_pkey')
    )
    # ### end Alembic commands ###
