"""Adding seeking talent and description to venue

Revision ID: af38a8f48730
Revises: 423b1e43055a
Create Date: 2020-04-19 18:56:58.028737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af38a8f48730'
down_revision = '423b1e43055a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.add_column('Venue', sa.Column('seeking_talent_desc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_talent_desc')
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###
